version: '3'

services:
  database:
    container_name: Database-Postgresql
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game
    ports:
      - "5432:5432"
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data/

  # backend:
  #   container_name: Backend-Golang

  # frontend:
  #   container_name: Frontend-Angular
  #   build: Frontend
  #   ports:
  #     - "4200:80"

networks:
  database_network:

volumes:
  database_volume:
